Repository jazzband/pip-tools, pull requests merged in 2019-09, with the labels that each got.

#893 Add feature request template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: maintenance

#897 Pin pytest!=5.1.2
  dev-requirements.txt
  tox.ini
Labels: bug fix, tests

#864 Add compatibility with the pip master (upcoming pip==19.3)
  .appveyor.yml
  .travis.yml
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_repositories.py
  tests/test_utils.py
  tox.ini
Labels: bug fix

#906 Allow failing PIP=19.3 until pip being released
  .appveyor.yml
  .travis.yml
Labels: maintenance, tests

#905 Add info to README about layered requirements files
  README.rst
Labels: docs

#904 Add compatibility with pip==19.3 for removed Link.is_artifact property
  piptools/repositories/pypi.py
Labels: bug fix

#910 Add compatibility with pip==19.3 for refactored URL helpers
  piptools/_compat/pip_compat.py
Labels: bug fix

#912 Fix create_command() import
  piptools/utils.py
Labels: bug fix
