Repository jazzband/pip-tools, pull requests merged in 2019-02, with the labels that each got.

#729 Added the release process to the Contributing guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: Documentation

#737 Fix pip-sync to use pip script depending on a python version
  piptools/sync.py
  tests/test_sync.py
Labels: Bug Fix

#741 Cleanup the pip_conf fixture
  tests/test_cli.py
Labels: Tests, Trivial

#742 Split test_cli.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/utils.py
Labels: Refactoring, Tests, Trivial

#740 Cleanup dead code
  piptools/utils.py
Labels: Trivial

#731 Fix the output file for pip-compile with an explicit setup.py as source file
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: Bug Fix

#745 Run codecov in appveyor ci
  .appveyor.yml
  .travis.yml
Labels: Maintenance

#749 Fix a regression bug came from #731 PR
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: Bug Fix, Trivial

#748 CI: baseline / fast finish
  .appveyor.yml
  .travis.yml
Labels: Maintenance
