Repository jazzband/pip-tools, pull requests merged in 2019-10, with the labels that each got.

#909 Ensure pip-compile --no-header <blank requirements.in> creates/overwrites requirements.txt
  piptools/writer.py
  tests/test_cli_compile.py
Labels: bug fix

#915 Fix url_to_path() import
  piptools/_compat/pip_compat.py
Labels: bug fix

#913 Add --ask option to pip-sync
  piptools/scripts/sync.py
  piptools/sync.py
  tests/test_cli_sync.py
  tests/test_sync.py
Labels: enhancement

#917 Add network mark for pytest
  setup.cfg
  tests/test_cli_compile.py
  tests/test_repository_local.py
  tests/test_repository_pypi.py
  tests/test_top_level_editable.py
Labels: tests, trivial

#914 Remove obsolete contributor checklist item in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#899 Remove redundant deps=piplatest declaration from tox
  tox.ini
Labels: maintenance

#922 Refactor several tests to reduce the time spent (issue #894)
  tests/test_cli_compile.py
  tests/test_data/minimal_wheels/small_fake_with_deps_a-0.1-py2.py3-none-any.whl
  tests/test_data/small_fake_with_deps_a/setup.py
Labels: refactor, tests

#930 Rename test packages dir to same names as the package names.
  tests/test_cli_compile.py
  tests/test_data/packages/fake_with_deps/setup.py
  tests/test_data/packages/small_fake_with_deps/setup.py
  tests/test_data/packages/small_fake_with_deps_a/setup.py
  tests/test_sync.py
  tests/test_top_level_editable.py
Labels: refactor, tests

#916 Add cron job for pipmaster env to GitHub actions
  .github/workflows/cron.yml
Labels: maintenance

#924 Add flaky mark to network tests in CI
  dev-requirements.txt
  tests/conftest.py
  tox.ini
Labels: maintenance, tests

#931 Fixed pip-compile --upgrade-package removes "via" annotation
  piptools/scripts/compile.py
  tests/test_cli_compile.py
  tests/test_data/minimal_wheels/small_fake_with_deps_a-0.1-py2.py3-none-any.whl
  tests/test_data/packages/small_fake_with_deps_a/setup.py
Labels: bug fix

#933 Use python-version instead of version in GitHub Actions
  .github/workflows/cron.yml
Labels: maintenance

#934 Add --no-index to pip_conf fixture to reduce testing time
  tests/test_cli_compile.py
Labels: tests

#936 Release 4.2.0
  CHANGELOG.md
Labels: maintenance

#939 Remove six dependency from small-fake-a==0.3b1
  tests/test_data/minimal_wheels/small_fake_a-0.3b1-py2.py3-none-any.whl
Labels: tests

#943 Use path_to_url() instead of _get_file_url()
  tests/test_sync.py
Labels: bug fix, refactor, tests

#941 Remove useless excludes from pre-commit config
  .pre-commit-config.yaml
Labels: maintenance

#945 Address TODO related to pip==19.3 release
  .appveyor.yml
  .travis.yml
  tox.ini
Labels: maintenance

#884 Fix formatting issues in README
  README.rst
Labels: docs

#940 Skip commands_pre for checkqa and readme env in tox.ini
  tox.ini
Labels: maintenance

#955 Fix python version from 3.7 to just 3
  .pre-commit-config.yaml
Labels: maintenance

#961 Remove dead code from test/conftest.py
  tests/conftest.py
Labels: refactor, tests

#962 Add test for FakeRepository.get_hashes()
  tests/test_fake_index.py
Labels: tests

#953 Fix compatibility with pip master
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
Labels: bug fix

#965 Call LocalRequirementsRepository.allow_all_wheels() in tests
  tests/test_repository_local.py
Labels: tests

#967 Refactor import statements in repositories/pypi.py
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
Labels: refactor

#970 Moving the tests from test_repositories.py to test_repository_pypi.py
  tests/test_repositories.py
  tests/test_repository_pypi.py
Labels: refactor, tests

#964 Fix --trusted-host is not copied from *.in to *.txt
  piptools/scripts/compile.py
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: bug fix
