Repository jazzband/pip-tools, pull requests merged in 2019-04, with the labels that each got.

#770 Add isort and black
  .flake8
  .travis.yml
  piptools/__main__.py
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/_compat/tempfile.py
  piptools/cache.py
  piptools/click.py
  piptools/exceptions.py
  piptools/locations.py
  piptools/logging.py
  piptools/pip.py
  piptools/repositories/base.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/sync.py
  piptools/utils.py
  piptools/writer.py
  setup.cfg
  setup.py
  tests/conftest.py
  tests/test_cache.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_data/fake_package/setup.py
  tests/test_data/small_fake_package/setup.py
  tests/test_fake_index.py
  tests/test_minimal_upgrade.py
  tests/test_repositories.py
  tests/test_repository_local.py
  tests/test_repository_pypi.py
  tests/test_resolver.py
  tests/test_sync.py
  tests/test_top_level_editable.py
  tests/test_utils.py
  tests/test_writer.py
  tests/utils.py
  tox.ini
Labels: Maintenance

#772 List the Python extension for VS Code as supporting requirements.txt syntax highlighting
  README.rst
Labels: Documentation

#777 Support the flag --trusted-host in pip-sync.
  piptools/scripts/sync.py
  tests/test_cli_sync.py
Labels: Enhancement

#774 Enable FussyFox for flake8 & isort
  .fussyfox.yml
  setup.cfg
Labels: Maintenance

#771 Exclude from coverage exception line
  tests/utils.py
Labels: Tests, Trivial

#778 Add pre-commit hooks
  .pre-commit-config.yaml
  .travis.yml
  CONTRIBUTING.md
  tox.ini
Labels: Maintenance

#779 Exclude common dirs from flake8
  setup.cfg
Labels: Maintenance

#780 Remove redundant noqa markers
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/writer.py
Labels: Trivial

#781 Assert mocked calls explicitly
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_sync.py
Labels: Refactoring, Tests

#775 Enable bandit security linter
  .bandit
  .fussyfox.yml
  piptools/cache.py
  piptools/sync.py
  piptools/utils.py
  tox.ini
Labels: Maintenance

#784 Add full test coverage for fs_str func
  piptools/utils.py
  tests/test_utils.py
Labels: Tests, Trivial

#795 Fix pip>=19.1 compatibility
  piptools/repositories/pypi.py
Labels: Bug fix, PIP

#798 Add options --cert and --client-cert to pip-sync
  piptools/scripts/sync.py
  tests/test_cli_sync.py
Labels: enhancement
