Repository jazzband/pip-tools, pull requests merged in 2019-03, with the labels that each got.

#750 Use pytest-cov plugin
  piptools/__main__.py
  tox.ini
Labels: Tests

#756 Add full test coverage for the writer module
  tests/test_writer.py
Labels: Tests

#757 Add full test coverage for the utils module
  piptools/utils.py
  tests/test_utils.py
Labels: Tests

#763 Write markers before hashes to fix issues.
  piptools/utils.py
  tests/test_utils.py
Labels: Bug Fix

#765 Show less output on sync with quiet option
  piptools/sync.py
  tests/test_cli_sync.py
  tests/test_sync.py
Labels: Enhancement

#767 Fix URL in readme
  README.rst
Labels: Documentation, Trivial

#760 Add 'requirements.txt.vim' to the other tools section of the README
  README.rst
Labels: Documentation

#752 ci: Travis: test pypy/pypy3 only with PIP=latest
  .travis.yml
Labels: Maintenance

#769 Cli tests refactoring
  tests/test_cli_compile.py
  tests/test_cli_sync.py
Labels: Refactoring, Tests

#766 Add full test coverage for the resolver module
  piptools/resolver.py
  tests/test_resolver.py
Labels: Tests, Trivial

#727 Use click API for output file handling in pip-compile
  piptools/_compat/__init__.py
  piptools/_compat/contextlib.py
  piptools/io.py
  piptools/scripts/compile.py
  piptools/utils.py
  piptools/writer.py
  tests/conftest.py
  tests/test_writer.py
Labels: Refactoring
