Repository jazzband/pip-tools, pull requests merged in 2019-08, with the labels that each got.

#863 Add retry wrapper to codecov command in CI
  .appveyor.yml
  .travis.yml
Labels: maintenance

#866 Update install_command in tox to force install up-to-date dependencies
  .appveyor.yml
  .travis.yml
  tox.ini
Labels: maintenance

#868 Install dependencies in tox with --upgrade option
  .appveyor.yml
  tox.ini
Labels: maintenance

#870 Format strings inside dedent
  tests/test_cli_compile.py
Labels: trivial

#869 Fix piplatest env
  .appveyor.yml
  tox.ini
Labels: maintenance

#871 Configure find-links in pip_conf fixture
  tests/test_cli_compile.py
Labels: refactoring, trivial

#872 Filter deprecation warnings from pip._vendor module
  setup.cfg
Labels: maintenance

#861 Prevent dry-run log message from being printed with --quiet option
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug fix

#879 Resolver.constraints: Keep our_constraints before their_constraints
  piptools/resolver.py
  tests/conftest.py
  tests/test_data/fake-editables.json
  tests/test_resolver.py
Labels: bug fix
