Repository jazzband/pip-tools, pull requests merged in 2019-11, with the labels that each got.

#978 Fix compatibility with pip master (pip>=19.4)
  piptools/repositories/pypi.py
Labels: bug fix

#984 Install fresh virtualenv on AppVeyor
  .appveyor.yml
Labels: bug fix, tests

#956 Add python 3.8 support
  .appveyor.yml
  .github/workflows/cron.yml
  .travis.yml
  setup.py
Labels: enhancement, maintenance

#986 Refactor-out unassertive OutputWriter() tests
  tests/test_writer.py
Labels: refactor, tests

#975 Unpin commented out unsafe packages
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: enhancement

#959 Add warn about requirements.txt file to "requirements without setup.py" section of readme
  README.rst
Labels: docs

#996 Moved global test constants to tests.constants module (issues_991).
  tests/constants.py
  tests/test_cli_compile.py
Labels: refactor, tests

#968 Cleanup ephemeral wheel cache properly
  piptools/repositories/pypi.py
  tests/test_repository_pypi.py
Labels: bug fix

#999 Clean up piptools/_vendored
  .coveragerc
  setup.cfg
  tests/__init__.py
Labels: maintenance

#997 Move changelog to the appropriate section
  CHANGELOG.md
Labels: docs

#1006 Update the release process guideline
  CONTRIBUTING.md
Labels: docs

#1004 Fix pip version from 19.4 to 20.0
  piptools/repositories/pypi.py
Labels: bug fix, trivial

#1007 Release 4.3.0.
  CHANGELOG.md
Labels: maintenance

#1008 Add .venv to .gitignore
  .gitignore
Labels: maintenance

#998 Reduce tests which require the network
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_data/minimal_wheels/small_fake_with_deps-0.1-py2.py3-none-any.whl
  tests/test_data/minimal_wheels/small_fake_with_deps_a-0.1-py2.py3-none-any.whl
  tests/test_data/packages/small_fake_with_deps/setup.py
  tests/test_data/packages/small_fake_with_deps_a/setup.py
  tests/test_repository_local.py
  tests/test_top_level_editable.py
Labels: refactor, tests

#1010 Use `PACKAGES_PATH` constants in tests.test_sync.test_diff_with_editable.
  tests/test_sync.py
Labels: refactor, tests

#1009 Remove excess parametrization decorator from `test_editable_top_level_deps_preserved` test.
  tests/test_top_level_editable.py
Labels: refactor, tests

#1011 Refactor test_generate_hashes_all_platforms to use local packages.
  tests/test_data/minimal_wheels/small_fake_multi_arch-0.1-py2.py3-none-manylinux1_i686.whl
  tests/test_data/minimal_wheels/small_fake_multi_arch-0.1-py2.py3-none-manylinux1_x86_64.whl
  tests/test_data/minimal_wheels/small_fake_multi_arch-0.1-py2.py3-none-win32.whl
  tests/test_repository_pypi.py
Labels: refactor, tests
