Repository jazzband/pip-tools, pull requests merged in 2019-07, with the labels that each got.

#837 Print provenance information when pip-compile fails
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/exceptions.py
  piptools/resolver.py
  tests/conftest.py
  tests/test_minimal_upgrade.py
  tests/test_resolver.py
Labels: enhancement

#839 Use pip-tools repo itself for VCS tests
  tests/test_cli_compile.py
Labels: tests, trivial

#840 Revisit README badges
  README.rst
Labels: documentation

#842 Fix output file update on dry-run compile
  piptools/utils.py
  tests/test_cli_compile.py
Labels: bug fix

#844 Ignore deprecation warnings from pip module
  setup.cfg
Labels: maintenance

#803 Drop python 3.4
  .appveyor.yml
  setup.py
Labels: maintenance

#857 Fix pip>=19.2 compatibility
  .appveyor.yml
  .travis.yml
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/pip.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_repositories.py
  tests/test_repository_local.py
  tests/test_repository_pypi.py
  tests/test_top_level_editable.py
  tox.ini
Labels: bug fix

#855 Update black repo URL
  .pre-commit-config.yaml
Labels: maintenance
