Repository jazzband/pip-tools, pull requests merged in 2019-05, with the labels that each got.

#791 Validate readme via twine check command
  setup.py
  tox.ini
Labels: maintenance

#790 Add full test coverage for the cache module
  piptools/cache.py
  tests/conftest.py
  tests/test_cache.py
Labels: tests

#789 Add full test coverage for the locations module
  tests/test_locations.py
Labels: tests

#743 Show progressbar on generation hashes in verbose mode
  piptools/_compat/contextlib.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  tests/test_cli_compile.py
  tests/test_repository_pypi.py
Labels: enhancement, log/console output

#793 Add support for --find-links in pip-compile output
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: enhancement

#808 Fix replacing password to asterisks in pip-compile
  piptools/utils.py
  tests/test_utils.py
Labels: bug fix

#800 Normalize «command to run» in pip-compile headers.
  piptools/__init__.py
  piptools/scripts/compile.py
  piptools/utils.py
  piptools/writer.py
  tests/conftest.py
  tests/test_utils.py
  tests/test_writer.py
Labels: enhancement

#812 Fix --generate-hashes with bare VCS URLs
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  tests/test_cli_compile.py
Labels: bug fix

#792 Check QA via pre-commit in tox
  .pre-commit-config.yaml
  tox.ini
Labels: maintenance

#814 Warn when --generate-hashes output is uninstallable
  piptools/writer.py
  tests/test_writer.py
Labels: enhancement

#821 Add a test for pip-compile --pre option
  tests/test_cli_compile.py
  tests/test_data/minimal_wheels/small_fake_a-0.3b1-py2.py3-none-any.whl
Labels: tests

#822 Respect --pre option in requirements.in file
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug fix
