Repository jazzband/pip-tools, pull requests merged in 2020-11, with the labels that each got.

#1229 Replace Travis CI with GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .travis.yml
  README.rst
  tox.ini
Labels: ci

#1216 Add pip>=20.3 support
  .appveyor.yml
  .github/workflows/ci.yml
  README.rst
  piptools/repositories/pypi.py
  tox.ini
Labels: enhancement

#1231 Release 5.4.0
  CHANGELOG.md
Labels: maintenance

#1223 Remove appveyor in favor of GitHub Actions
  .appveyor.yml
  README.rst
Labels: ci

#1239 Combine adjacent strings on one line
  tests/test_cli_compile.py
Labels: trivial

#1222 Complete testing and documentation of Python 3.9 support
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  setup.cfg
Labels: enhancement

#1238 Remove unnecessary envvar configuration in click options
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  tests/test_cli_compile.py
Labels: cli

#1240 Remove six dependency in favor pip's vendored six
  piptools/_compat/__init__.py
  piptools/repositories/base.py
  piptools/utils.py
  piptools/writer.py
  setup.cfg
  tests/test_utils.py
Labels: dependency, pip, refactor

#1241 Unify sync's logging with compile's logging system
  piptools/scripts/sync.py
  piptools/sync.py
  tests/test_sync.py
Labels: cli, enhancement

#1232 Disable fail-fast in GHA workflows
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
Labels: ci

#1245 Minor fixes to stay in line with Jazzband CI best practices
  .github/workflows/release.yml
Labels: ci

#1250 Use os.path.dirname() to get the path's parent directory
  tests/constants.py
Labels: tests, trivial

#1251 Delay indexing option.opts until its use in get_compile_command()
  piptools/utils.py
Labels: trivial

#1246 Doc supported Python versions in README.rst
  README.rst
Labels: docs

#1244 Docs: Add pip-requirements.el (for Emacs) to useful tools
  README.rst
Labels: docs, trivial
