Repository jazzband/pip-tools, pull requests merged in 2020-01, with the labels that each got.

#1022 Add --cache-dir option to pip-compile
  piptools/cache.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_top_level_editable.py
  tests/test_utils.py
Labels: enhancement, refactor, tests

#1024 Add pip>=20.0 support
  .appveyor.yml
  .travis.yml
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  tox.ini
Labels: enhancement

#1031 pip-compile -P PKGSPEC ignores pkgs not already parsed as constraints
  piptools/scripts/compile.py
  tests/test_cli_compile.py
  tests/test_data/minimal_wheels/small_fake_with_unpinned_deps-0.1-py2.py3-none-any.whl
  tests/test_data/packages/small_fake_with_unpinned_deps/setup.py
Labels: bug fix

#1032 Add full test coverage for the exceptions module
  tests/test_cli_compile.py
Labels: tests

#1035 Do the basic configuration of the builtin logging module
  piptools/logging.py
Labels: bug fix, logging

#1039 Upgrade click version in setup.py
  setup.py
Labels: bug fix

#1029 Fix a bug where pip-compile would keep outdated options
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug fix

#1040 Pin pip to 20.0.x release in tox.ini
  tox.ini
Labels: maintenance

#1023 pip-tools should be installed in the project's virtual environment
  README.rst
Labels: docs

#1044 Add how to install requirements on different stages to Workflow for layered requirements section.
  README.rst
Labels: docs

#1037 Fix missing dependencies of relevant constraints
  README.rst
  piptools/resolver.py
  tests/test_cli_compile.py
  tests/test_data/fake-index.json
  tests/test_data/minimal_wheels/small_fake_with_deps_and_sub_deps-0.1-py2.py3-none-any.whl
  tests/test_data/packages/small_fake_with_deps_and_sub_deps/setup.py
  tests/test_resolver.py
Labels: bug fix, resolver

#1026 Use str.format instead of printf-style formatting
  piptools/resolver.py
Labels: refactor, trivial

#1050 include the implementation in the depcache
  piptools/cache.py
Labels: bug fix, cache

#1052 Release 4.4.1
  CHANGELOG.md
Labels: maintenance
