Repository jazzband/pip-tools, pull requests merged in 2020-07, with the labels that each got.

#1175 Do not search for best_match for -c constraints that are not (yet) requirements
  piptools/resolver.py
  tests/test_resolver.py
Labels: enhancement, resolver

#1177 Ignore local hashes with --no-reuse-hashes
  piptools/repositories/local.py
  piptools/scripts/compile.py
  tests/test_repository_local.py
Labels: cli, enhancement

#1172 Update sync to return non-zero exit code on dry run
  piptools/sync.py
  tests/test_cli_sync.py
Labels: enhancement

#1168 Add pip>=20.2 support
  .github/workflows/ci.yml
  .travis.yml
  piptools/repositories/pypi.py
  tox.ini
Labels: enhancement

#1186 Release 5.3.0
  CHANGELOG.md
Labels: maintenance

#1194 Make RequirementSummary equality and hash unsentive to version format variation
  piptools/resolver.py
  tests/test_resolver.py
  tox.ini
Labels: bug fix, resolver

#1195 Release 5.3.1
  CHANGELOG.md
Labels: maintenance
