Repository jazzband/pip-tools, pull requests merged in 2020-06, with the labels that each got.

#1159 Local repository needs to notify proxied repo of ireq copying
  piptools/repositories/base.py
  piptools/repositories/local.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_repository_local.py
Labels: bug fix

#1161 Release 5.2.1
  CHANGELOG.md
Labels: maintenance

#1162 Use make_package for better test isolation
  tests/test_cli_compile.py
Labels: refactor, tests

#1163 Add -h alias for --help option
  piptools/scripts/compile.py
  piptools/scripts/sync.py
Labels: cli, enhancement

#1169 Add py3.9 to CI workflow
  .github/workflows/ci.yml
  tox.ini
Labels: ci
