Repository jazzband/pip-tools, pull requests merged in 2020-02, with the labels that each got.

#1053 Replace outdated link with rationale for pinning
  README.rst
Labels: docs

#1062 Normalize cache_dir path to be compatible with pip v20
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  tests/test_repository_pypi.py
Labels: bug fix

#1068 Some cleanup
  piptools/repositories/local.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cache.py
Labels: trivial

#1058 Annotate primary requirements and VCS dependencies
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: enhancement

#1071 Release 4.5.0
  CHANGELOG.md
Labels: maintenance

#1072 Updated README example outputs for primary req annotations
  README.rst
Labels: docs

#1075 Strip line number annotations
  README.rst
  piptools/writer.py
  tests/test_cli_compile.py
Labels: bug fix

#1078 Release 4.5.1
  CHANGELOG.md
Labels: maintenance

#1081 flake8 ignore E203; see https://github.com/psf/black#slices
  setup.cfg
  tests/test_resolver.py
Labels: trivial
