Repository jazzband/pip-tools, pull requests merged in 2020-03, with the labels that each got.

#1082 Unpin tox in AppVeyor config
  .appveyor.yml
Labels: trivial

#1055 Pin pip-tools to pip>=20.0
  .appveyor.yml
  .travis.yml
  README.rst
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/locations.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/sync.py
  piptools/utils.py
  setup.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_repository_pypi.py
  tests/test_sync.py
  tests/test_utils.py
  tests/test_writer.py
  tox.ini
Labels: backwards incompatible, deprecation, refactor

#1060 Make the --build-isolation flag set on by default for pip-compile.
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  tests/test_utils.py
Labels: backwards incompatible, cli, enhancement

#923 Unify development requirements
  CONTRIBUTING.md
  dev-requirements.txt
  setup.py
  tox.ini
Labels: maintenance, refactor

#824 Support options in requirements.txt in pip-sync
  piptools/scripts/sync.py
  tests/test_cli_sync.py
Labels: enhancement

#1086 Fix post-merge conflicts
  piptools/scripts/sync.py
Labels: bug fix

#976 Add pre-commit hook for pip-compile
  .pre-commit-hooks.yaml
  README.rst
Labels: enhancement

#651 Added cross-environment usage documentation to README.rst
  README.rst
Labels: docs

#1094 Suggest "pip install --upgrade" using module invocation in README
  README.rst
Labels: docs, trivial
