Repository jazzband/pip-tools, pull requests merged in 2020-12, with the labels that each got.

#1257 Handle TODO comments in tox.ini now that pip 20.3 was released
  tox.ini
Labels: tests, trivial

#1258 Remove unused environment variable PIP from tox.ini
  tox.ini
Labels: tests, trivial

#1255 Use context manager to restore environment variables in resolve()
  piptools/resolver.py
Labels: enhancement, refactor

#1254 Remove now-unnecessary PIP_REQ_TRACKER cleanup
  piptools/repositories/pypi.py
Labels: refactor

#1260 Upgrade codecov action to v1.0.15
  .github/workflows/ci.yml
Labels: ci, tests

#1253 Avoid spurious output during tests
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_repository_local.py
  tests/test_repository_pypi.py
  tests/test_sync.py
  tests/test_utils.py
  tests/test_writer.py
Labels: maintenance, tests

#1252 Remove filterwarnings configuration
  setup.cfg
Labels: maintenance, tests, trivial

#1264 Use more descriptive exceptions than AssertionError
  piptools/cache.py
  piptools/utils.py
  tests/test_cache.py
  tests/test_utils.py
Labels: trivial

#1269 Simplify uses of InstallRequirement
  piptools/utils.py
Labels: trivial

#1268 Remove unnecessary coerce to str
  piptools/repositories/pypi.py
Labels: trivial

#1267 Fix typo: unnecessarely → unnecessarily
  piptools/repositories/pypi.py
Labels: trivial

#1266 Remove unnecessary system calls via os.path.exists()/os.path.isdir()
  piptools/_compat/__init__.py
  piptools/cache.py
  piptools/repositories/pypi.py
  tests/test_cache.py
  tests/test_compat.py
Labels: enhancement

#1272 Add coverage for "if not is_pinned_requirement(…)" in get_hashes()
  tests/test_repository_pypi.py
Labels: tests, trivial

#1274 Update isort URL in .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: ci, trivial

#1273 Update pre-commit hooks
  .pre-commit-config.yaml
  piptools/scripts/sync.py
Labels: ci, trivial

#1281 Release 5.5.0
  CHANGELOG.md
Labels: maintenance

#1225 Remove long deprecated LEGACY_CACHE_DIR
  piptools/locations.py
  tests/test_locations.py
Labels: backwards incompatible
