Repository jazzband/pip-tools, pull requests merged in 2020-04, with the labels that each got.

#1098 Sort format controls to ensure consistent results
  piptools/utils.py
  piptools/writer.py
  tests/test_writer.py
Labels: bug fix, writer

#1093 Compile editables that are both primary reqs and constraints
  piptools/resolver.py
  tests/test_cli_compile.py
Labels: bug fix

#1088 Add pip>=20.1 support
  .appveyor.yml
  .travis.yml
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/utils.py
  tests/test_repository_pypi.py
  tox.ini
Labels: enhancement

#1090 Remove build_isolation param from PyPIRepository constructor
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: refactor

#1105 Fix a bug where pip-compile would downgrade a resolved prerelease version
  piptools/repositories/local.py
  tests/test_cli_compile.py
Labels: bug fix, resolver

#1101 Add a test for uncovered branch in the writer module
  tests/test_writer.py
Labels: refactor, tests, writer

#1106 Add a versions compatibility table to README
  README.rst
Labels: docs

#1080 Pass arbitrary args to 'pip' from pip-compile and pip-sync, with '--pip-args'
  README.rst
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_utils.py
Labels: cli, enhancement

#927 Exclude requirements with non-matching markers from pip-sync's merge stage
  piptools/sync.py
  tests/test_cli_sync.py
Labels: enhancement, needs discussion

#1108 Release 5.0.0
  CHANGELOG.md
Labels: maintenance

#1112 Pin pip-20.1 and its betas in tox and CIs
  .appveyor.yml
  .travis.yml
  tox.ini
Labels: maintenance

#1110 Indent logs with a context manager
  piptools/logging.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  tests/test_logging.py
Labels: logging, refactor

#1109 Get hashes from PyPI JSON API
  piptools/repositories/pypi.py
  tests/test_repository_pypi.py
Labels: enhancement

#949 Show progress bar when downloading package in verbose mode
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/logging.py
  piptools/repositories/pypi.py
Labels: enhancement, logging

#1117 Refactor to for-else block
  piptools/repositories/pypi.py
Labels: refactor

#1120 Release 5.1.0
  CHANGELOG.md
  README.rst
Labels: maintenance

#1122 Ignore eggs hashes from PyPI JSON API
  piptools/repositories/pypi.py
  tests/test_repository_pypi.py
Labels: bug fix

#1125 Release 5.1.1
  CHANGELOG.md
Labels: maintenance
