Repository jazzband/pip-tools, pull requests merged in 2020-05, with the labels that each got.

#1091 Use click API to test the output from click.echo()
  piptools/sync.py
  tests/test_sync.py
Labels: refactor, tests

#1136 Release 5.1.2
  CHANGELOG.md
Labels: maintenance

#1143 Adopt flake8-pytest-style
  .pre-commit-config.yaml
  setup.cfg
  tests/conftest.py
  tests/test_cache.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_fake_index.py
  tests/test_repository_pypi.py
  tests/test_sync.py
  tests/test_utils.py
  tests/test_writer.py
Labels: ci, maintenance, refactor

#1144 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: bug fix, maintenance

#1012 Add CI workflow for GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
  tests/conftest.py
  tests/utils.py
  tox.ini
Labels: ci, maintenance

#1147 Fix broken cron CI job
  .github/workflows/cron.yml
Labels: bug fix, ci

#1119 Fix a bug where pip-compile would ignore some of versions if prefer binary distributions
  piptools/repositories/pypi.py
  tests/conftest.py
  tests/test_cli_compile.py
Labels: bug fix, resolver

#1146 Fix leaked URLs with credentials in the output
  piptools/exceptions.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: bug fix, logging

#1113 Show basename of hashing URL in debug logs
  piptools/repositories/pypi.py
Labels: enhancement, logging

#1151 Fix py27 failing jobs
  .appveyor.yml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .travis.yml
Labels: bug fix, ci

#1149 Avoid URL requirement name collisions
  piptools/repositories/pypi.py
  tests/conftest.py
  tests/test_repository_pypi.py
Labels: bug fix

#1130 Deprecate --index/--no-index in pip-compile
  README.rst
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_utils.py
  tests/test_writer.py
Labels: cli, deprecation, enhancement

#1152 Release 5.2.0
  CHANGELOG.md
Labels: maintenance
