Repository jazzband/pip-tools, pull requests merged in 2021-09, with the labels that each got.

#1477 Enable single-line annotations with `pip-compile --annotation-style=line`
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: annotations, feature

#1488 Release 6.3.0
  CHANGELOG.md
  README.rst
Labels: skip-changelog

#1489 Xfail `test_realistic_complex_sub_dependencies` on PyPy under Windows
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1492 Improve clarity of help text for options supporting multiple
  piptools/scripts/compile.py
  piptools/scripts/sync.py
Labels: bug

#1493 Allow comma-separated arguments for --extra
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug
