Repository jazzband/pip-tools, pull requests merged in 2021-06, with the labels that each got.

#1408 Fixed typing
  .pre-commit-config.yaml
  piptools/scripts/compile.py
  setup.cfg
Labels: ci, maintenance, pip

#1351 Add type annotations for FileStream()
  piptools/repositories/pypi.py
Labels: trivial

#889 Add missing dependencies to the setup.cfg
  setup.cfg
Labels: enhancement, needs discussion

#1410 Fix click v7 version_option compatibility
  piptools/scripts/compile.py
  piptools/scripts/sync.py
Labels: bug fix

#828 Log which python version was used during compile
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: enhancement, needs discussion

#1409 Disable codecov comments
  codecov.yml
Labels: ci

#1387 Document updating requirements with pre commit hooks
  README.rst
Labels: docs, pre-commit

#1333 Support custom python-executable
  piptools/scripts/sync.py
  piptools/subprocess_utils.py
  piptools/sync.py
  piptools/utils.py
  tests/test_cli_sync.py
  tests/test_subprocess_utils.py
  tests/test_utils.py
Labels: cli, enhancement

#1419 Fix pip-compile package ordering
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: bug fix, writer

#1123 Add --emit-options/--no-emit-options flag
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_utils.py
  tests/test_writer.py
Labels: cli, enhancement

#1379 Add PyPy jobs to PR CI runs
  .github/workflows/ci.yml
  tests/test_cli_compile.py
Labels: ci, maintenance

#1416 Add release drafter github action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
Labels: maintenance

#1425 Prettify CHANGELOG file
  .prettierrc.yaml
  CHANGELOG.md
Labels: maintenance

#1426 Make GitHub recognise BSD 3-clause license
  LICENSE
  setup.cfg
Labels: skip-changelog

#1424 Fix changelog category title template
  .github/release-drafter.yml
Labels: maintenance

#1423 Release 6.2.0
  CHANGELOG.md
Labels: maintenance
