Repository jazzband/pip-tools, pull requests merged in 2021-04, with the labels that each got.

#1374 Test pip against the `main` default branch
  .github/workflows/cron.yml
  tox.ini
Labels: ci, tests

#1381 Add correct space after venv label
  README.rst
Labels: docs, trivial

#1363 Extra requirement support (extras_require)
  piptools/scripts/compile.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: enhancement, pep-517

#1362 Release 6.1.0
  CHANGELOG.md
Labels: maintenance

#1378 Set up caching PyPI deps in GHA
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
Labels: ci, enhancement, maintenance

#1369 Better explain role of existing requirements.txt
  README.rst
Labels: docs, enhancement
