Repository jazzband/pip-tools, pull requests merged in 2021-01, with the labels that each got.

#1284 Fix typo: differentation → differentiate
  piptools/cache.py
Labels: trivial

#1283 Remove contextlib.nullcontext compat shim in favor of pip's version
  piptools/_compat/contextlib.py
  piptools/repositories/pypi.py
Labels: trivial

#1285 Remove unnecessary util function force_text()
  piptools/utils.py
  tests/test_utils.py
Labels: trivial

#1286 Remove pypy2 from CI cron workflow
  .github/workflows/cron.yml
  tox.ini
Labels: ci

#1287 Add pyupgrade to pre-commit config
  .pre-commit-config.yaml
Labels: ci

#1288 Remove language restrictions in pre-commit config
  .pre-commit-config.yaml
  tox.ini
Labels: trivial

#1290 Add test for format_specifier() with editable requirements
  tests/test_utils.py
Labels: tests, trivial

#1294 Remove unused member OutputWriter.src_files
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_writer.py
Labels: trivial

#1299 Remove duplicate test_editable_top_level_deps_preserved test
  tests/test_top_level_editable.py
Labels: tests, trivial

#1308 Add missing assert keyword to test
  tests/test_sync.py
Labels: tests, trivial
