Repository jazzband/pip-tools, pull requests merged in 2021-02, with the labels that each got.

#1315 Add typing to several areas where straightforward
  piptools/__main__.py
  piptools/_compat/pip_compat.py
  piptools/cache.py
  piptools/exceptions.py
  piptools/logging.py
  piptools/repositories/base.py
  piptools/resolver.py
  piptools/sync.py
  piptools/utils.py
  tests/test_cache.py
  tests/test_utils.py
Labels: trivial

#1317 Run `pre-commit autoupdate`
  .pre-commit-config.yaml
Labels: dependency, trivial

#1289 Use prettier pre-commit hook for md, json, and yaml formatting
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  tests/test_data/fake-index.json
Labels: ci, trivial

#1318 Enable mypy option no_implicit_reexport
  piptools/_compat/__init__.py
  piptools/repositories/__init__.py
  setup.cfg
Labels: trivial

#1316 Add type hints for the resolver module
  piptools/cache.py
  piptools/repositories/base.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/utils.py
  tests/test_resolver.py
  tests/test_utils.py
Labels: trivial

#1325 Write out default index when it is provided as`--extra-index-url`
  piptools/writer.py
  tests/test_writer.py
Labels: bug fix

#1324 Fix compiling input setup file in nested folders
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug fix, setuptools

#1323 Consider specifiers for equality operator to pin a dependency in make_install_requirement
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
Labels: bug fix, resolver

#1331 Add type hints for the sync module
  piptools/scripts/sync.py
  piptools/sync.py
Labels: trivial
