Repository jazzband/pip-tools, pull requests merged in 2021-03, with the labels that each got.

#1234 Remove deprecated "--index/--no-index" option from compile command
  README.rst
  piptools/scripts/compile.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: backwards incompatible, cli, deprecation

#1334 Remove unused name_from_req()
  piptools/utils.py
  tests/test_minimal_upgrade.py
  tests/test_repository_local.py
  tests/test_utils.py
Labels: trivial

#1311 Use pep517 to load project metadata
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement, setuptools

#1338 Revert back piptools._compat.contextlib
  piptools/_compat/contextlib.py
  piptools/repositories/pypi.py
Labels: trivial

#1343 Prefer dict literals over dict constructor
  piptools/repositories/pypi.py
  tests/test_minimal_upgrade.py
Labels: trivial

#1341 Complete type hinting of piptools.repositories package
  piptools/_compat/contextlib.py
  piptools/cache.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/utils.py
  tests/test_utils.py
Labels: trivial

#1345 Prefer dict over OrderedDict
  piptools/utils.py
Labels: trivial

#1347 Fix a bug where pip-compile setup.py would fail due to URL dependency
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug fix, setuptools

#1322 Add typings for the scripts.compile module
  piptools/repositories/base.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/scripts/compile.py
  piptools/utils.py
  piptools/writer.py
  tests/conftest.py
Labels: trivial

#1349 Release 6.0.0
  CHANGELOG.md
Labels: maintenance

#1350 Enable disallow_untyped_defs for mypy
  setup.cfg
Labels: trivial

#1353 Declare pep517 dependency
  piptools/scripts/compile.py
  setup.cfg
Labels: bug fix, dependency

#1354 Release 6.0.1
  CHANGELOG.md
Labels: maintenance

#1357 Parallelize pytest runs
  setup.cfg
Labels: tests

#1356 PEP-517 support
  .gitignore
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement, pep-517, setuptools

#1366 Fix year in release dates of 6.* versions to 2021
  CHANGELOG.md
Labels: docs

#1368 Restore ability to set compile cache with env var PIP_TOOLS_CACHE_DIR
  piptools/scripts/compile.py
Labels: bug fix
