Repository jazzband/pip-tools, pull requests merged in 2022-04, with the labels that each got.

#1607 Add support for pip==22.1
  .github/workflows/ci.yml
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  piptools/resolver.py
Labels: enhancement

#1540 Fix --generate-hashes when hashes are computed from files
  piptools/repositories/pypi.py
  tests/test_data/minimal_wheels/small-fake-multi-arch-0.1.tar.gz
  tests/test_repository_pypi.py
Labels: bug

#1592 Ensure `pip-compile --dry-run --quiet` still shows what would be done, while omitting the dry run message
  piptools/writer.py
  tests/test_cli_compile.py
Labels: bug

#1609 Release 6.6.0
  CHANGELOG.md
Labels: maintenance, skip-changelog
