Repository jazzband/pip-tools, pull requests merged in 2022-12, with the labels that each got.

#1748 Release 6.11.0
  CHANGELOG.md
  README.rst
Labels: maintenance, skip-changelog

#1759 Support tox v4
  tox.ini
Labels: skip-changelog

#1758 Update link for tox devenv doc
  CONTRIBUTING.md
Labels: skip-changelog

#1761 Fix failing tests that depend on a logger verbosity level
  piptools/logging.py
  tests/conftest.py
Labels: tests, skip-changelog

#1765 Restore coloring for console and CI
  .github/workflows/ci.yml
  tox.ini
Labels: skip-changelog

#1745 Add `--no-index` flag to `pip-compile`
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement, cli

#1763 Adopt PEP-621 for packaging
  .flake8
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: bug

#1768 Enable TOML reformatting in prettier
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog

#1766 Filter out the user provided unsafe packages
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: bug

#1770 Fix CI after switching to pyproject.toml
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
  .github/workflows/release.yml
Labels: ci, skip-changelog

#1771 Fix build CI job
  .github/workflows/release.yml
Labels: ci, skip-changelog

#1578 Treat `--upgrade-packages` PKGSPECs as constraints (not just minimums), consistently
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug

#1774 Add test: ignore unavailable versions in preexisting output
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1775 Release 6.12.0
  CHANGELOG.md
  README.rst
Labels: maintenance

#1776 Improve text of resolver warning
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: skip-changelog

#1782 Set explicitly packages for setuptools
  pyproject.toml
Labels: bug

#1784 Fix setuptools warning
  pyproject.toml
Labels: skip-changelog

#1783 Release 6.12.1
  CHANGELOG.md
Labels: maintenance

#1788 Fix a regression with unsafe packages for `--allow-unsafe`
  piptools/writer.py
  tests/test_cli_compile.py
Labels: bug

#1780 Add `pyproject.toml` as default input file format
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug

#1787 Raise error if input and output filenames are matched
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug
