Repository jazzband/pip-tools, pull requests merged in 2022-10, with the labels that each got.

#1649 Fix compile cached vcs packages
  piptools/resolver.py
Labels: bug fix, resolver

#1682 Introduce a gate/check GHA job
  .github/workflows/ci.yml
Labels: tests, maintenance, ci, skip-changelog

#1690 Upgrade action versions in the main workflow
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
  .github/workflows/release.yml
Labels: tests, maintenance

#1692 Send env-specific flags to Coverage from GHA
  .github/workflows/ci.yml
Labels: skip-changelog

#1664 Refactor `Resolver._get_install_requirements()`
  piptools/resolver.py
Labels: refactor, skip-changelog

#1693 Update changelog for 6.9.0 release
  CHANGELOG.md
Labels: skip-changelog

#1652 Add --newline=[LF|CRLF|native|preserve] to compile
  piptools/scripts/compile.py
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: enhancement

#1614 Fix some EncodingWarnings in python 3.10 (PEP 597)
  piptools/cache.py
Labels: bug

#1694 use tmp_path for test_override_newline
  tests/test_cli_compile.py
Labels: skip-changelog

#1708 Add support for Python 3.11 final
  .github/workflows/ci.yml
  setup.cfg
Labels: enhancement
