Repository jazzband/pip-tools, pull requests merged in 2022-05, with the labels that each got.

#1619 Release 6.6.1
  CHANGELOG.md
Labels: maintenance

#1620 fix typo in readme
  README.rst
Labels: skip-changelog

#1624 Update PyPIRepository::resolve_reqs() for pip>=22.1.1
  piptools/repositories/pypi.py
Labels: bug

#1625 Cancel running jobs when a pull request is updated
  .github/workflows/ci.yml
  .github/workflows/qa.yml
Labels: skip-changelog

#1519 Instantiate a new accumulator InstallRequirement for combine_install_requirements output
  piptools/resolver.py
  tests/test_cli_compile.py
  tests/test_resolver.py
Labels: bug fix, resolver
