Repository jazzband/pip-tools, pull requests merged in 2022-06, with the labels that each got.

#1632 Support for the importlib.metadata metadata implementation
  piptools/_compat/pip_compat.py
  piptools/scripts/sync.py
  piptools/sync.py
  tests/conftest.py
Labels: feature

#1629 Replace direct usage of the `pep517` module with the `build` module, for loading project metadata
  piptools/scripts/compile.py
  setup.cfg
  tests/conftest.py
  tests/test_cli_compile.py
Labels: dependency

#1644 Release 6.7.0
  CHANGELOG.md
Labels: maintenance

#1588 Update contributing guide
  CONTRIBUTING.md
Labels: skip-changelog

#1539 Add support for pip's 2020 dependency resolver
  piptools/repositories/base.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/utils.py
  piptools/writer.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_resolver.py
  tests/test_top_level_editable.py
Labels: enhancement, resolver

#1646 Release 6.8.0
  CHANGELOG.md
Labels: maintenance
