Repository jazzband/pip-tools, pull requests merged in 2022-11, with the labels that each got.

#1687 Add regression test for GH-1647
  tests/conftest.py
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1713 Fix inconsistent handling of constraints comments with backtracking resolver
  piptools/resolver.py
  tests/test_cli_compile.py
Labels: bug, resolver

#1701 Update pip-tools version in the README's pre-commit examples
  README.rst
Labels: docs

#1695 configure isort to add `from __future__ import annotations`
  docs/conf.py
  piptools/__init__.py
  piptools/__main__.py
  piptools/_compat/__init__.py
  piptools/_compat/click.py
  piptools/_compat/pip_compat.py
  piptools/cache.py
  piptools/exceptions.py
  piptools/locations.py
  piptools/logging.py
  piptools/repositories/__init__.py
  piptools/repositories/base.py
  piptools/repositories/local.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/subprocess_utils.py
  piptools/sync.py
  piptools/utils.py
  piptools/writer.py
  setup.cfg
  setup.py
  tests/conftest.py
  tests/constants.py
  tests/test_cache.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_data/packages/fake_with_deps/setup.py
  tests/test_data/packages/small_fake_a/setup.py
  tests/test_data/packages/small_fake_with_deps/setup.py
  tests/test_data/packages/small_fake_with_deps_and_sub_deps/setup.py
  tests/test_data/packages/small_fake_with_subdir/subdir/setup.py
  tests/test_data/packages/small_fake_with_unpinned_deps/setup.py
  tests/test_fake_index.py
  tests/test_logging.py
  tests/test_minimal_upgrade.py
  tests/test_repository_local.py
  tests/test_repository_pypi.py
  tests/test_resolver.py
  tests/test_subprocess_utils.py
  tests/test_sync.py
  tests/test_utils.py
  tests/test_writer.py
  tests/utils.py
Labels: skip-changelog

#1719 Prompt user to use the backtracking resolver on errors
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement, resolver

#1725 Use explicit output requirement file to test the exact output
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1724 Deprecate `pip-compile --resolver=legacy`
  README.rst
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: deprecation, resolver

#1728 Test on Python 3.12
  .github/workflows/cron.yml
  tox.ini
Labels: ci, skip-changelog

#1722 Release 6.10.0
  CHANGELOG.md
  README.rst
Labels: maintenance

#1726 Replace deprecated set-output in GHA
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/qa.yml
Labels: ci, skip-changelog

#1729 Bump pip minimum version to `>= 22.2`
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  piptools/resolver.py
  setup.cfg
  tox.ini
Labels: dependency

#1732 Make slowest test_override_newline x90 faster
  tests/test_cli_compile.py
Labels: tests

#1727 Support build isolation using `setuptools/pyproject.toml` requirement files
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement, setuptools, pep-517, pyproject.toml

#1643 Adding pyproject.toml file
  .github/workflows/release.yml
  pyproject.toml
Labels: bug

#1733 Bump click minimum version to `>= 8`
  piptools/_compat/__init__.py
  piptools/_compat/click.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  setup.cfg
Labels: dependency

#1723 Generate hashes for all available candidates
  piptools/repositories/pypi.py
  tests/test_cli_compile.py
  tests/test_repository_pypi.py
Labels: bug, hashes

#1735 Speedup tests using `--no-build-isolation`
  setup.cfg
  tests/conftest.py
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1547 Improve punctuation/grammar with header.
  piptools/writer.py
  tests/test_cli_compile.py
  tests/test_writer.py
Labels: bug, writer

#1736 Fix CI tests on Windows against pip main branch
  tox.ini
Labels: ci, skip-changelog

#1740 Replace master with main branch
  .github/workflows/ci.yml
  .github/workflows/qa.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.rst
  tests/test_utils.py
Labels: skip-changelog

#1739 Replace `master` with `main` where possible
  .github/workflows/cron.yml
  .github/workflows/qa.yml
  tests/test_repository_pypi.py
Labels: skip-changelog

#1744 Use v1 of GitHub action `pypa/gh-action-pypi-publish`
  .github/workflows/release.yml
Labels: ci, skip-changelog
