Repository jazzband/pip-tools, pull requests merged in 2023-05, with the labels that each got.

#1851 Add pyprojects.toml example for using setuptools
  README.rst
Labels: docs

#1847 Correct in README `pre-commit` hook to run off `requirements.in`
  README.rst
Labels: docs

#1864 Update Python on RTD to v3.11
  .readthedocs.yaml
Labels: bug, docs, skip-changelog

#1843 Use covdefaults
  .coveragerc
  piptools/__main__.py
  pyproject.toml
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1822 Log a warning if the user specifies -P and the output file is present but empty
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: logging, enhancement

#1872 Add docs preview env for `tox`
  tox.ini
Labels: docs, maintenance, enhancement
