Repository jazzband/pip-tools, pull requests merged in 2023-08, with the labels that each got.

#1943 Fix typo (`vor -> for`)
  README.md
Labels: skip-changelog

#1945 Update CHANGELOG text structure
  CHANGELOG.md
Labels: bug, docs, skip-changelog

#1947 Release 7.2.0
  CHANGELOG.md
  README.md
Labels: maintenance, skip-changelog

#1949 Tweak wording
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#1948 Document that the backtracking resolver is the current default
  README.md
Labels: docs

#1950 Remove outdated compatibility matrix from `README`
  README.md
Labels: docs, skip-changelog

#1951 Document how to run under `pipx run`
  README.md
Labels: docs

#1955 Use stdout as an output in test_compile_recursive_extras
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#1582 Direct references show extra requirements in .txt files
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: bug, extras

#1904 Fix revealed default config in header if requirements in subfolder
  piptools/locations.py
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_utils.py
Labels: bug, config

#1954 Add `--no-strip-extras` and warn about strip extras by default
  README.md
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: enhancement

#1958 Release 7.3.0
  CHANGELOG.md
  README.md
Labels: maintenance

#1952 Move cli options definitions to `piptools.scripts.options` module
  piptools/scripts/compile.py
  piptools/scripts/options.py
  piptools/scripts/sync.py
Labels: refactor, skip-changelog

#1961 💄 Show 20 slowest tests in pytest report
  pyproject.toml
Labels: skip-changelog

#1962 👷 Prevent tox pkg double build @ GHA
  .github/workflows/ci.yml
  .github/workflows/reusable-qa.yml
Labels: skip-changelog

#1967 Update tox environments
  .github/workflows/ci.yml
  tox.ini
Labels: skip-changelog

#1970 Disable coverage report on PyPy tests job
  .github/workflows/ci.yml
  tox.ini
Labels: ci, skip-changelog

#1963 Speed up tests execution
  pyproject.toml
  tests/conftest.py
  tests/test_cli_compile.py
Labels: skip-changelog

#1972 Remove py37 from tox.ini
  tox.ini
Labels: skip-changelog

#1973 Comment on `pytest --dist=worksteal` usage
  pyproject.toml
Labels: tests, skip-changelog

#1969 Setup reproducible docs builds using pip-tools
  docs/requirements.in
  docs/requirements.txt
  tox.ini
Labels: skip-changelog

#1976 Exclude pre-commit ci from release notes
  .github/release-drafter.yml
Labels: ci, skip-changelog
