Repository jazzband/pip-tools, pull requests merged in 2023-07, with the labels that each got.

#1895 🔧 Ignore PyPy 3.7 test outcome in CI
  .github/workflows/ci.yml
Labels: ci, skip-changelog

#1893 Exclude default config value from the pip-compile header
  piptools/utils.py
  tests/conftest.py
  tests/test_utils.py
Labels: skip-changelog

#1894 Downgrade log level for configuration defaults message
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
Labels: skip-changelog

#1879 Drop support for Python 3.7
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependency, backwards incompatible, ci

#1890 Fix missing `via`s when more than two input files are used
  piptools/resolver.py
  tests/test_cli_compile.py
Labels: bug

#1885 Sync direct references with hashes
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/scripts/sync.py
  piptools/sync.py
  piptools/utils.py
  tests/conftest.py
  tests/test_sync.py
Labels: enhancement, skip-changelog, sync

#1896 Add `--no-config` option
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
Labels: enhancement, cli

#1841 Promote #pip-tools chat on pypa discord server
  README.md
Labels: skip-changelog

#1900 ⇪👷 Bump re-actors/alls-green to v1.2.2
  .github/workflows/ci.yml
Labels: ci, skip-changelog

#1899 👷 Deduplicate cron GHA through workflow reuse
  .github/workflows/ci.yml
  .github/workflows/cron.yml
Labels: skip-changelog

#1901 🎨🔧👷 Wire in linters into the main workflow
  .github/workflows/ci.yml
  .github/workflows/reusable-qa.yml
Labels: ci, skip-changelog

#1906 Add support for `pip==23.2` where refactored out `DEV_PKGS`
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/sync.py
Labels: enhancement

#1897 Default to `--resolver=backtracking`
  piptools/scripts/compile.py
Labels: resolver, backwards incompatible

#1912 Don't use setuptools_scm from Sphinx itself
  docs/conf.py
  pyproject.toml
  tox.ini
Labels: docs, skip-changelog

#1910 Validate parsed config against click command params
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
  tests/test_utils.py
Labels: enhancement

#1919 Fix a bug where pip-sync would unexpectedly uninstall some packages
  piptools/sync.py
  tests/conftest.py
  tests/test_sync.py
Labels: bug

#1922 Release 7.1.0
  CHANGELOG.md
  README.md
Labels: maintenance

#1934 Add Command Line Reference section to docs
  docs/cli/index.md
  docs/cli/pip-compile.md
  docs/cli/pip-sync.md
  docs/conf.py
  docs/index.md
  docs/requirements.txt
Labels: docs

#1915 Refactor multi-value options validation
  piptools/utils.py
  tests/test_utils.py
Labels: refactor, skip-changelog, config

#1933 Allow options in config from both `pip-compile` and `pip-sync`
  piptools/utils.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
Labels: bug, config

#1936 Add `-c/--constraint` option to `pip-compile`
  README.md
  piptools/scripts/compile.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_utils.py
Labels: feature, cli

#1940 Remove dead code
  piptools/utils.py
Labels: refactor, skip-changelog

#1941 Unshallow git clone on RTD build
  .readthedocs.yaml
Labels: docs, skip-changelog
