Repository jazzband/pip-tools, pull requests merged in 2023-03, with the labels that each got.

#1815 Release 6.12.3
  CHANGELOG.md
  README.rst
Labels: maintenance

#1814 Fix minor typos in the README
  README.rst
Labels: docs, skip-changelog

#1817 Fix year in changelog entry
  CHANGELOG.md
Labels: skip-changelog

#1828 Add support for `pip==23.1` where deprecated `--install-option` has been removed
  piptools/utils.py
Labels: enhancement

#1832 Add support for `pip==23.1` where refactored requirement options
  tests/conftest.py
  tests/test_repository_local.py
  tests/test_sync.py
  tests/test_utils.py
Labels: enhancement
