Repository jazzband/pip-tools, pull requests merged in 2023-11, with the labels that each got.

#2011 Filter out origin ireqs for extra requirements before writing output annotations
  piptools/writer.py
  tests/test_cli_compile.py
Labels: bug, writer

#1681 Add options for including build dependencies in compiled output
  .pre-commit-config.yaml
  README.md
  examples/readme/constraints.txt
  examples/readme/pyproject.toml
  piptools/build.py
  piptools/scripts/compile.py
  piptools/scripts/options.py
  piptools/utils.py
  pyproject.toml
  tests/conftest.py
  tests/test_build.py
  tests/test_cli_compile.py
  tests/test_data/packages/small_fake_with_build_deps/backend/backend.py
  tests/test_data/packages/small_fake_with_build_deps/pyproject.toml
  tests/test_data/packages/small_fake_with_build_deps/setup.py
Labels: enhancement

#1989 Fix ignorance of inverted CLI options in config for `pip-sync`
  piptools/utils.py
  tests/test_cli_compile.py
Labels: bug, config
