Repository jazzband/pip-tools, pull requests merged in 2023-04, with the labels that each got.

#1834 Add support for pip==23.1 where removed FormatControl in WheelCache
  piptools/_compat/__init__.py
  piptools/_compat/pip_compat.py
  piptools/repositories/pypi.py
  piptools/resolver.py
Labels: enhancement

#1827 Pass `--cache-dir` to `--pip-args` for backtracking resolver
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug

#1835 Update examples in README
  README.rst
Labels: docs

#1791 Add support for self-referential extras
  .pre-commit-config.yaml
  piptools/_compat/pip_compat.py
  piptools/scripts/compile.py
  piptools/utils.py
  tests/test_cli_compile.py
Labels: enhancement

#1844 Release 6.13.0
  CHANGELOG.md
  README.rst
Labels: maintenance
