Repository jazzband/pip-tools, pull requests merged in 2024-02, with the labels that each got.

#2055 Fix failing test on pip-24.0
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#2054 Release 7.4.0
  CHANGELOG.md
  README.md
Labels: maintenance

#1981 🐛 Fix collecting deps for all extras in multiple input packages
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug, extras
