Repository jazzband/pip-tools, pull requests merged in 2024-01, with the labels that each got.

#1966 Add support for command-specific configuration sections
  README.md
  piptools/scripts/compile.py
  piptools/scripts/sync.py
  piptools/utils.py
  tests/conftest.py
  tests/test_cli_compile.py
  tests/test_cli_sync.py
Labels: feature, config

#2041 Allow force-enabling or force-disabling colorized output
  piptools/scripts/compile.py
  piptools/scripts/options.py
Labels: logging, feature, cli

#2039 Add a test which checks that fifos outputs are not read
  tests/test_cli_compile.py
Labels: tests, skip-changelog

#2042 Ignore matrix badges in ci linkcheck-docs
  docs/conf.py
Labels: docs, tests, maintenance, skip-changelog

#2015 Fix for `src-files` not being used when specified in a config file
  piptools/scripts/compile.py
  tests/test_cli_compile.py
Labels: bug, config
